In [7]:
import numpy as np

In [8]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)

In [9]:
arr * 4

array([ 80, 108,  36,  48, 124,  68,  16, 200, 156, 140])

In [10]:
print(np.mean(arr))

24.4


In [11]:
print(np.median(arr))

23.5


In [12]:
print(np.std(arr))

13.828955130450023


In [13]:
print(np.argmin(arr))

6


In [14]:
print(np.argmax(arr))

7


In [15]:
print(arr[np.argmin(arr)])

4


In [16]:
print(arr[np.argmax(arr)])

50


In [17]:
print(np.min(arr))

4


In [18]:
print(np.max(arr))

50


In [19]:
print(arr[arr > 20])

[27 31 50 39 35]


In [20]:
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]

In [21]:
arr1 = np.array(matrix)


In [22]:
arr1.shape

(3, 4)

In [23]:
print(arr1[:, 2])

[17 14 19]


In [24]:
print(arr1[1])

[ 8 21 14  3]


In [25]:
print(arr1 * 2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [26]:
print(arr1.mean(axis=0))

[ 6.33333333 15.33333333 16.66666667  7.66666667]


In [27]:
print(np.mean(arr1))

11.5


In [28]:
print(arr1.max(axis=1))

[17 21 19]


In [29]:
print(arr1.min(axis=0))

[ 5 12 14  3]


In [33]:
arr1.flatten()

array([ 5, 12, 17,  9,  8, 21, 14,  3,  6, 13, 19, 11])

In [34]:
np.argmin(arr1.flatten())

np.int64(7)

In [35]:
np.argmax(arr1.flatten())

np.int64(5)

In [44]:
np.unravel_index(np.argmin(arr1.flatten()), arr1.shape)

(np.int64(1), np.int64(3))

In [45]:
np.unravel_index(np.argmax(arr1.flatten()), arr1.shape)

(np.int64(1), np.int64(1))

In [46]:
print(arr1[arr1 > 15])

[17 21 19]


In [47]:
np.sort(arr1, axis=1)

array([[ 5,  9, 12, 17],
       [ 3,  8, 14, 21],
       [ 6, 11, 13, 19]])

In [48]:
arr2 = np.array([

[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]

])


In [49]:
def is_prime(n):    
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

In [50]:
def rows_with_prime(array):
    result = []
    for row in array:
        for num in row:
            if is_prime(num):
                result.append(row)
                break
    return result

In [51]:
rows_with_prime(arr2)

[array([2, 3, 5]), array([11, 13, 17]), array([ 7, 10, 13])]

In [53]:
board = np.zeros((8,8),dtype=int)

In [56]:
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, ::2] = 1   
    board[1::2, 1::2] = 1
    return board

print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [59]:
def reverse_checkerboard():
    board1 = np.ones((8, 8), dtype=int)
    board1[::2, ::2] = 0   
    board1[1::2, 1::2] = 0
    return board1

print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [61]:
def expansion(words, spaces):
    result = []
    for word in words:
        result.append((" " * spaces).join(word))
    return np.array(result)

universe = np.array(['galaxy', 'clusters'])

print(expansion(universe, 1))
print(expansion(universe, 2))

['g a l a x y' 'c l u s t e r s']
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [62]:
def secondDimmest(stars):
    return np.sort(stars)[:, -2]

In [63]:
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))

print(stars)
print(secondDimmest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
